## 1. Installing required software and background

##### 1.1 Create workspace
# create/close project
# panel layout (Tools--Global Options--Panel Layout)
# save script

##### 1.2 Set working directory  
# set work directory: setwd("file_path") or setwd(file.choose()) to manually select a path   
# get work directory: getwd()  

setwd("~/OneDrive - National Institutes of Health/Documents/BCBB training course/2024_R")
getwd()

## 2 Operator


#create variable
a = 2
a <- 2

#logical 
a < - 2
a == 2
a <= 2

#arithmetic expressions
x <- 2 * a
y1 <- 2 * (a + log(x)) #default natural logarithm
y2 <- 2 * (a + log(x, base = exp(1))) #specify base
y3 <- 2 * (a + log10(x))
y4 <- 2 * (a + log2(x))

#round numbers
y <- round(y1,4)

#create numerical vector
x <- rnorm(10) #random generate a vector that length = 10, standard normal distribution
x[2] #extract a value from vector based on the index
x[2:7] #subset the vector

#create charactor vector
x <- c("apple","pear","peach","watermelon","banana")
x[2]
x[-1] #remove an element from vector based on the index
a = "apple"
a %in% x #check if element is in a vector

#create factor vector
risk <- c(rep("high",20), rep("medium", 30),rep("low",10))
risk1 <- factor(risk)
risk2 <- factor(risk, levels = c("high","medium","low"))

#create list,which could contains multiple different type of elements
L = list()
L[[1]] = "apple"
L[[2]] = c(1:5)
L[[3]] = TRUE
L[[4]] = matrix(rnorm(10),2,5)

#assign the name to each element
names(L) = c("L_Character","L_Number","L_Logical","L_Matrix") 
#extract an element from list by its name
L$L_Number 
#extract an element from list by its index
L[[2]] 

#create matrix
A <- matrix(data = runif(24, min= -1, max = 1), nrow = 4, ncol = 6)
A[2,5] #extract a value from matrix based on the row and column index
A[1:2,] #extract first two rows from matrix
A[,-c(1,3)] #remove 1st, 3rd columns from matrix

#create data frame
D <- data.frame(age = c(2,1,4,3,5), 
                animal = c("dog","cat","sheep","panda","tiger"), 
                ifmale = c(T,F,T,F,T), 
                weight = c(5.2,2.2,30.5,124.1,90.3))
row.names(D) = c("sample1","sample2","sample3","sample4","sample5") #assign row name 
D$animal #subset one variable
D[D$ifmale==T,] #subset rows with condition
D[D$ifmale==T & D$weight>10,] #subset rows with multiple conditions
D[D$ifmale!=T | D$age<=2,] #subset rows with multiple conditions


#remove objects from current environment
rm(A)
remove(A)
A

## 3. Installing R packages

##### 3.1 
#method 1
# The install.packages function is used to install new R packages via command line
# We will use it to install cranlogs that can tell us about how many times an R package is downloaded
install.packages("cranlogs")
#install packacges once
install.packages(c("readr", "dplyr", "Stat2Data","ggplot2")) # install multiple packages

#method 2
#alternative way to install packages
#"Packages" --> "Install" --> e.g."BiocManager"

#method 3
#install from website
#e.g. Bioconductor
#Bioconductor is a free, open source and open development software project for the analysis and comprehension of genomic data generated by wet lab experiments in molecular biology.

#method 4
#Install a package from Github
#GitHub is a repository useful for all software development and data analysis, including R packages. It makes sharing your package easy. You can read more about GitHub here: Git and GitHub, by Hadley Wickham.
#To install a package from GitHub, the R package devtools (by Hadley Wickham) can be used. You should first install devtools if you don’t have it installed on your computer.
#For example, the following R code installs the latest version of survminer R package developed by A. Kassambara (https://github.com/kassambara/survminer).
#rare case
install.packages("devtools")
devtools::install_github("kassambara/survminer")


#load packages everytime when you run project
library(survminer)
library(readr)
library(readxl)
library(dplyr)
library(Stat2Data)
library(ggplot2)
library(MASS)
library(BiocManager)
library(dplyr)

##### 3.2 Let's use `cranlogs` package to determine how many downloads `ggplot2` package has 
## To load an R package, we use the library function
library(cranlogs)

## Lets see how many downloads ggplot2 had in 2021
ggplot2_dls <- cran_downloads(packages = "ggplot2", from = "2023-01-01", to = "2023-12-31")

# We can see that the average daily downloads of ggplot2 is over 80k!
mean(ggplot2_dls$count)

##### 3.3 Check version of R and loaded packages
sessionInfo() 

##### 3.4 help information
#Documentation Shortcuts
?print
help("print")

#Search the Help System
??print
help.search("print") 

## 4. Dataset import and export
#click:
#  Step1: "Import Dataset"
#  Step2: "From Text(base)...",for txt and csv files, doesn't work for excel file
#         "From Text(readr)...",for txt and csv files, doesn't work for excel file, provide code and preview of imported dataframe (Recommend)
#         "From Excel...",for excel file, provide code and preview of imported dataframe (Recommend)

#load corresponding package for different type of data files.
#choose appropriate function and specify the type of variable in the dataset.

library(readr)
#text file
framingham.txt <- read.delim("framingham.txt")
framingham.txt <- read_delim("framingham.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
#csv file
framingham.csv <- read.csv("framingham.csv")

#excel file
library(readxl)
framingham.xlsx <- read_excel("framingham.xlsx")

#export file
write.csv(x = framingham.csv, file = "framingham_test.csv", row.names = F) 
# If you do not specify row.names = F then the row names will be written out, there are other function inputs you can look up using help(write.csv)

## 5. Basic data manipulations

#dimension of dataframe
dim(framingham.csv)
#basic summary of variables
summary(framingham.csv)
#see all variable type
sapply(framingham.csv, class)
#displays the internal structure of an object such as an array, list, matrix, factor, or data frame
str(framingham.csv)
#first six (default) rows of the data
head(framingham.csv)
head(framingham.csv,n = 10)

#check missing value
is.na(framingham.csv)
#count the number of missing values
sum(is.na(framingham.csv)) 
#count the number of missing value for each column
colSums(is.na(framingham.csv)) 
#remove rows/observations that contains missing value
framingham = na.omit(framingham.csv)
dim(framingham)
summary(framingham)

#focus on one variable
education <- framingham$education
mean(education) # average
sd(education) # standard deviation
sum(education) # summation

unique(education) # return all unique value in factor
length(unique(education)) # return the number of unique value in factor

#convert to factor/categorical variable
summary(education) #summary of numerical variable
education = factor(education)
summary(education) #summary of categorical variable
table(education) # same as summary() for categorical variable

#subset dataframe based on condition
#subset column
# select three columns: education, BMI, male
select <- framingham[,c("education", "BMI", "male")]

#subset row
#method 1
framingham.male = framingham[framingham$male==1,]
framingham.male.obesity= framingham[framingham$male==1 & framingham$BMI >=30,]

#method 2
framingham.male = subset(framingham, male == 1)

#arrange  
# Order the data by ascending age and education
head(arrange(framingham, age))
head(arrange(framingham, age, education))

# Order age by descending
head(arrange(framingham, desc(age)))

#create new variable
framingham$gender <- ifelse(framingham$male==1, "Male", "Female"); gender = framingham$gender
summary(gender)
gender = factor(gender, levels = c("Male", "Female")) #convert to factor variable
summary(gender)

#merge dataframe (Adding Rows)
framingham.male = subset(framingham, male == 1)
framingham.female = subset(framingham, male == 0)
framingham.mergerow = rbind(framingham.male,framingham.female)

#merge dataframe (Adding Columns)
framingham$id = paste0("Sample_",c(1:nrow(framingham)))
framingham.1 = framingham[,c(1:5,18)] #subset 1~5 variables with sample_id
framingham.2 = framingham[,c(6:10,18)] #subset 6~10 variables with sample_id
framingham.mergecol <- merge(framingham.2,framingham.2,by="id")

## 6. Data Structure conversion

### 6.1 Dataset with repeated measures
olddata_wide <- read.table(header=TRUE, text='
 subject sex control cond1 cond2
       1   M     7.9  12.3  10.7
       2   F     6.3  10.6  11.1
       3   F     9.5  13.1  13.8
       4   M    11.5  13.4  12.9
')
# Make sure the subject column is a factor
olddata_wide$subject <- factor(olddata_wide$subject)

#from wide to long
#method 1
library(tidyr)
data_long1 <- gather(olddata_wide, condition, measurement, control:cond2, factor_key=TRUE)
data_long1 <- gather(olddata_wide, condition, measurement, control, cond1, cond2)

#method 2
library(reshape2)
# Specify id.vars: the variables to keep but not split apart on
data_long2 <- melt(olddata_wide, id.vars=c("subject", "sex"), variable.name="condition", value.name="measurement")

#from long to wide
olddata_long <- read.table(header=TRUE, text='
 subject sex condition measurement
       1   M   control         7.9
       1   M     cond1        12.3
       1   M     cond2        10.7
       2   F   control         6.3
       2   F     cond1        10.6
       2   F     cond2        11.1
       3   F   control         9.5
       3   F     cond1        13.1
       3   F     cond2        13.8
       4   M   control        11.5
       4   M     cond1        13.4
       4   M     cond2        12.9
')
# Make sure the subject column is a factor
olddata_long$subject <- factor(olddata_long$subject)
#method 1
data_wide1 <- spread(olddata_long, condition, measurement)

#method 2
data_wide2 <- dcast(olddata_long, subject + sex ~ condition, value.var="measurement")

## 7. Execute externel R script
##### 7.1  run and save objects from externel R script
source("Hello_world.R")

##### 7.2  run and save functions defined from externel R script
source("functions.R")

#add function with return

#find mode value from vector education
mode(education)
table(education)

#calculate circle_area with radius = 5
r = 5
circle_area(r)
#calculate circumference with radius = 5
circumference(r)
#print the result in a sentence
print(paste0("For circle with r = ", r, ", the area of circle is ", round(circle_area(r),4), ", there circumference of circle is ",round(circumference(r),4), "." ))

#check sign of value
check(10)

## 8. Exercise questions

#### 8.0 Check the current path